### ISSUE TITLE
Planck EZ support, and what could be done to get Javelin under 256kb?

### ISSUE THREAD

**Issue by Beethoven-n** [jthlim/javelin-steno#10]
I'm running into the limits of what Plover is able to support (x11's slow death will probably drag Plover's linux client with it,) but I already bought a TinyMod, which has no onboard memory.

However, I _do_ use a Planck EZ, which has... admittedly very limited memory. ZSA told me direct in an email that it has 256kb of memory.

It doesn't sound good, but with an extremely minimal dictionary, I did see someone build a 400kb image. Is it possible to cut that down further, so it fits? What would have to be done?

**Comment by jthlim** [comment]
Javelin will never be under 256kb

The firmware is more than half of that just for the executable. The English words lookup used for orthographic suffixes is almost 4MB

The minimum javelin will support is 8MB, and 16MB is recommended
