### ISSUE TITLE
No parentheses in visual editor

### ISSUE THREAD

**Issue by tom-mcivor** [jthlim/javelin-steno#12]
I was just exploring the key select options in visual editor and noticed unless I'm mistaken there's no parentheses keys

**Comment by jthlim** [comment]
That's because there's no parenthesis keys on any keyboard. There's shift 9 and shift 0 though

**Comment by jthlim** [comment]
These have now been added for convenience.

![Screenshot 2024-07-14 at 4 01 10 AM](https://github.com/user-attachments/assets/84af4ac4-06c2-49af-91f6-d8e2603e7941)
