### ISSUE TITLE
Keyboard Layout Issue

### ISSUE THREAD

**Issue by evanjrowley** [jthlim/javelin-steno#13]
Hello, can you please help me or let me know where else I should ask about this? I am a new Javelin Steno user and am having a hard time with the Keyboard Layout options.

The Javelin keyboard works unlike any other keyboard I've used in regards to the Keyboard Layout options. With QMK or ZMK for example, selecting a Dvorak layout means the keyboard's QWERTY layer will be replaced with a Dvorak layer. This enables the user to type in their preferred layout without having to change the OS default. This does not seem to be the case with Javelin. Below is what I've observed.

Situation No. 1 - If Javelin's Keyboard Layout is Dvorak & OS Dvorak keymap is _not_ activated:
- Using Javelin's steno engine results in incorrect characters.
- Javelin still has a QWERTY layer instead of a Dvorak layer, and using it results in incorrect characters.
- Using Javelin's Symbol layer results in some correct keys and some incorrect wrong keys.

Situation No. 2 - If Javelin's Keyboard Layout is Dvorak & the OS Dvorak keymap is activated:
- Using Javelin's steno engine results in correct characters.
- Using Javelin's QWERTY layer results in QWERTY characters.
- Using Javelin's Symbol layer results in correct characters.

Situation No. 3 - If Javelin's Keyboard Layout is _not_ Dvorak & OS Dvorak keymap is activated:
- Using Javelin's steno engine results in incorrect characters.
- Using Javelin's QWERTY layer results in Dvorak characters.
- Using Javelin's Symbol layer results in some correct keys and some incorrect wrong keys.

I think I understand what's going on here. It looks like the Keyboard Layout options do not provide "hardware" implementations of those layouts, but instead, those options are so the Javelin firmware will be able to output the correct keys whenever those layers are activated.

The Javelin firmware would be a lot more useful to me if it worked more seamlessly with my preferred Keyboard Layout. Are either of these feasible?
- Replace the QWERTY layer with a preferred Keyboard Layout so that it would work as expected under Situation No. 1.
- Change the QWERTY layer so that the resulting characters are Dvorak under Situation No. 2.
- Adjust the Symbols layer so that it would be more compatible with a preferred Keyboard Layout under Situation No. 3.

**Comment by evanjrowley** [comment]
Closing this issue because I found answers to this in #9

**Comment by jthlim** [comment]
Please note that you can now set up your preferred keyboard configuration using the visual editor, rather than having to edit scripts. This is available in two places -- on the firmware builder page under expert options -> Edit Layout; and under the web tools -> Script tool -> Visual Editor.

![Screenshot 2024-08-07 at 9 57 21 AM](https://github.com/user-attachments/assets/18208313-66d2-4123-96ea-cb887216a1a2)

**Comment by evanjrowley** [comment]
Excellent! Thank you for creating amazing firmware and tools
