### ISSUE TITLE
Add Workman to keyboard layouts

### ISSUE THREAD

**Issue by robintown** [jthlim/javelin-steno#3]
When I'm not writing with steno, I use the Workman keyboard layout. But Javelin doesn't support this layout, which means I have to switch my computer's input method back to QWERTY every time I want to return to my steno machine. I'd appreciate it if Javelin could save me this step :)

**Comment by jthlim** [comment]
Implemented in https://github.com/jthlim/javelin-steno/commit/347708816a549f7c7077e7beb40a83531c8adacd

Online firmware builder and tools have been updated too.
