### ISSUE TITLE
Unable to connect device for Firmware tools

### ISSUE THREAD

**Issue by reikrom** [jthlim/javelin-steno#4]
Uni v4
    Chrome Version 109.0.5414.119 (Official Build) (64-bit)
    Running on Fedora 37
	Firmware works after using builder tool
	Device shows up
![image](https://user-images.githubusercontent.com/44064758/218212132-27a1e0aa-f363-4883-9fb1-d5fcb5cbce3b.png)
When I try to connect I get `NotAllowedError: Failed to open the device.`
![Screenshot from 2023-02-11 00-27-19](https://user-images.githubusercontent.com/44064758/218212980-e111cf14-c3de-4f68-8eae-526d3b7df1f6.png)

I went to chrome privacy settings and made sure HID, USB, and port permissions are not blocked as per [google FAQ.](https://support.google.com/chrome/answer/12576972?visit_id=638116638763070324-3429721221&p=webhid&rd=1#webhid&zippy=%2Clearn-more-about-hid-devices-in-chrome)
Chrome dev console doesn't have any other errors.

**Comment by reikrom** [comment]
Works on mac os, Closing as it's a Fedora issue

**Comment by jthlim** [comment]
Great! You can also set up a udev rule like:

SUBSYSTEM=="hidraw", ATTRS{idVendor}=="9000", ATTRS{idProduct}=="400d", MODE="0666"

And it'll have the correct permissions even after disconnecting/reconnecting or when rebooting.
