### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by mhmdanas** [jthlim/javelin-steno#5]
Title. I know the online firmware builder exists, but I'd prefer to build the firmware myself locally.

**Comment by jthlim** [comment]
Literally the very first link in the readme.me takes you to build instructions for Pico SDK

**Comment by mhmdanas** [comment]
Well, I have no idea what pico-sdk is, and there is no indication that this pico-sdk bindings thing is what I need. Anyway, thank you for the reference.
