### ISSUE TITLE
`{ }{-|}` outputs `{ }`

### ISSUE THREAD

**Issue by PaulColeman** [jthlim/javelin-steno#7]
0. Use plover's `main.json` or DI's `dict.json` or make sure the stroke `KPA` is defined as `{ }{-|}`
1. Open Notepad
2. Stroke `KPA` `KAT`

Result: `{ } Cat` is output
Expected: ` Cat` (a space the next word is caps)

Version: The Uni (Javelin) uni-v4-2023-04-28
 
https://user-images.githubusercontent.com/1077541/235510900-dff52492-ac63-4087-a67d-ec53532b3372.mp4

**Comment by jthlim** [comment]
Please use `{}{-|}` to do this (no space in the first group), which is the default in commands.json, and is documented in https://github.com/openstenoproject/plover/wiki/Dictionary-Format

`{ }` (with a space) may work, but is undocumented in the format.

**Comment by PaulColeman** [comment]
To complete the loop on this, Di has updated the dictionary repo: https://github.com/didoesdigital/steno-dictionaries/issues/576
