### ISSUE TITLE
Unicode output error with Emily's symbols for Δ

### ISSUE THREAD

**Issue by PaulColeman** [jthlim/javelin-steno#8]
0. Turn on Emily's symbols, enable `EnableHexNumpad`, and use `windows_hex` unicode mode
1. Start Notepad
2. Chord `SKWHEFB` (the Δ symbol)

Result: `'`
Expected: `Δ`

Note, using emily's symbols in plover does output the `Δ` as expected. 

Also, not sure if this is related but chording `SKWHEUFB` for the `∞` symbol in Visual Code, the Edit menu opens and no symbol is added. Using plover does output the symbol as expected.

**Comment by jthlim** [comment]
Are you able to type hex unicode with a normal keyboard?

i.e. Alt+0394?

I checked, and I'm emitting all the right scan codes; but I haven't got a Windows machine to test against easily.
![Screenshot 2023-05-05 at 10 05 51 PM](https://user-images.githubusercontent.com/16397552/236481817-58732d63-065e-4b59-a5c5-ab2b55d5b59e.png)

**Comment by PaulColeman** [comment]
It appears that it is notepad being strange in the case of delta. If I use
the ALT code or embedded mode I get the same behavior in Notepad. It works
as expected in other text inputs in other apps.

However, there does appear to be an issue using hex mode for hex code's
that include letters. This isn't specific to your implementation, but a
generic problem in Window. Here's an example: infinity has a hex code
of 0x221E. To enter it at one point you'll need to key down E, while the
ALT key is also down which is going to get interpreted by many windows apps
as the command to drop the edit menu. That's what is happening in Visual
studio code. And it happens in many other apps.

There are some application specific tricks to get around this but no
generic solution that I can thinking of. I suspect plover is getting around
this by sending the actual unicode character, running in user mode, rather
than keyboard input via HID.

I guess this no worse than the unicode story for a keyboard on Windows. If
there was user code running — could be limited to these unicode scenarios
only — it would make the Unicode story much better on Windows.

**Comment by jthlim** [comment]
Yeah, there's nothing that can be done from Javelin's side in this case - it's just a limitation of having to use HID, and HID not having a proper unicode story yet.

Plover can interact with the operating system in a much deeper way than Javelin can - it definitely isn't being held back by the limitations of HID.

Going to close this as there's nothing that's behaving unexpectedly from the firmware perspective
